---

# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
aptcachetime: 3600
locale: "en_EN.UTF-8"
timezone: "Europe/London"
chromium:
  set_default: true
  policy: false
  extensions: false
desktop_autostart:
  add: []
  remove:
    - deja-dup-monitor.desktop
    - onboard-autostart.desktop
    - orca-autostart.desktop
    - vino-server.desktop
ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false
