---

- name: Set npm global packages path
  command: npm config set prefix "{{ ansible_env.HOME }}/.npm-packages"

- name: Installs Bower globally using npm
  npm: name=bower state=present global=yes
