---

- name: Ubuntu desktop environment playbook
  hosts: localhost
  vars:
    aptcachetime: 3600
    locale: "fr_FR.UTF-8"
    timezone: "Europe/Paris"
    virtualbox:
      version: "5.0"
    vagrant:
      deb_url: "https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb"
    ruby:
      version: "2.2"
  roles:
    # - locales
    # - common
    # - zsh
    # - nodejs
    # - gulp
    # - browsersync
    # - bower
    # - ruby
    - vagrant
