---

dependencies: []

galaxy_info:
  author: Mark Olliver
  description: Ansible role to install slack on Ubuntu
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - "16.04"
  categories:
    - system
