---

- name: Add apt keys of spotify
  apt_key: keyserver=keyserver.ubuntu.com id=0DF731E45CE24F27EEEB1450EFDC8610341D9410

- name: Add repository
  apt_repository: repo="deb http://repository.spotify.com stable non-free"

- name: Install spotify
  apt: name=spotify-client update_cache=yes state=latest
