---

- name: Enable all repositories in sources.list
  replace:
    dest: /etc/apt/sources.list
    regexp: '^#\s?deb(.+)http://(.+)/ubuntu(.+)$'
    replace: 'deb\1http://\2/ubuntu\3'
    backup: yes
  become: true

- name: Ensure that Aptitude repositories are up to date
  apt: update_cache=yes
  become: true

- name: Upgrade installed packages
  apt: upgrade=safe
  become: true

- name: Install common packages
  become: true
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - build-essential
    - bzip2
    - cowsay
    - curl
    - diffutils
    - dos2unix
    - fortune
    - ftp
    - ftp-ssl
    - gcc
    - git
    - grep
    - gzip
    - htop
    - httping
    - iftop
    - iotop
    - less
    - make
    - nano
    - nmap
    - openssl
    - p7zip
    - pwgen
    - rsync
    - software-properties-common
    - sshpass
    - tar
    - tmux
    - unzip
    - vim
    - wget
    - whois
    - zip
