---

- name: Install common packages
  become: true
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - build-essential
    - bzip2
    - cowsay
    - curl
    - diffutils
    - dos2unix
    - fortune
    - ftp
    - ftp-ssl
    - gcc
    - git
    - grep
    - gzip
    - htop
    - httping
    - iftop
    - iotop
    - less
    - make
    - nano
    - nmap
    - openssl
    - p7zip
    - pwgen
    - rsync
    - software-properties-common
    - sshpass
    - tar
    - tmux
    - unzip
    - vim
    - wget
    - whois
    - zip
