---

- name: Add Elasticsearch apt key.
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present
  become: true

- name: Add Elasticsearch repository.
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main' state=present update_cache=yes
  become: true

- name: Install Elasticsearch.
  apt: pkg=elasticsearch state=present
  become: true

- name: Configure Elasticsearch.
  lineinfile: dest=/etc/elasticsearch/elasticsearch.yml regexp="{{ item.regexp }}" line="{{ item.line }}" state=present
  with_items:
    - { regexp: '^script\.disable_dynamic', line: 'script.disable_dynamic: true' }
    - { regexp: 'network\.host', line: 'network.host: localhost' }
  notify: Restart elasticsearch
  become: true

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled={{ elasticsearch.service_enabled }}
  when: elasticsearch.start == true
  become: true
