---

- name: Add brightbox Ruby repository
  apt_repository: repo="ppa:brightbox/ruby-ng" state=present

- name: Install Ruby {{ ruby.version }} and Ruby gems
  apt: pkg=ruby{{ ruby.version }} state=present
